ersion: '3.1'
#comando para acessar fora do container: mysql -u root -h 127.0.0.1 --port 3303 -p
services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

    volumes:
      - "./script/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3303:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
